//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_WEBKYSO.MdmsService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.mdms.ftu.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.mdms.ftu.com/", ConfigurationName="MdmsService.mdms_service")]
    public interface mdms_service {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/getBCTData_NgayRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/getBCTData_NgayResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ES_WEBKYSO.MdmsService.getBCTData_NgayResponse getBCTData_Ngay(ES_WEBKYSO.MdmsService.getBCTData_NgayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/getBCTData_NgayRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/getBCTData_NgayResponse")]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getBCTData_NgayResponse> getBCTData_NgayAsync(ES_WEBKYSO.MdmsService.getBCTData_NgayRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/getListBCTData_NgayRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/getListBCTData_NgayResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ES_WEBKYSO.MdmsService.getListBCTData_NgayResponse getListBCTData_Ngay(ES_WEBKYSO.MdmsService.getListBCTData_NgayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/getListBCTData_NgayRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/getListBCTData_NgayResponse")]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getListBCTData_NgayResponse> getListBCTData_NgayAsync(ES_WEBKYSO.MdmsService.getListBCTData_NgayRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/getBillingDataFromMDMSRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/getBillingDataFromMDMSResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ES_WEBKYSO.MdmsService.Exception), Action="http://service.mdms.ftu.com/mdms_service/getBillingDataFromMDMS/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ES_WEBKYSO.MdmsService.getBillingDataFromMDMSResponse getBillingDataFromMDMS(ES_WEBKYSO.MdmsService.getBillingDataFromMDMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/getBillingDataFromMDMSRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/getBillingDataFromMDMSResponse")]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getBillingDataFromMDMSResponse> getBillingDataFromMDMSAsync(ES_WEBKYSO.MdmsService.getBillingDataFromMDMSRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/getBillingSpcFromMDMSRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/getBillingSpcFromMDMSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSResponse getBillingSpcFromMDMS(ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/getBillingSpcFromMDMSRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/getBillingSpcFromMDMSResponse")]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSResponse> getBillingSpcFromMDMSAsync(ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/helloRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ES_WEBKYSO.MdmsService.helloResponse hello(ES_WEBKYSO.MdmsService.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/helloRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/helloResponse")]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.helloResponse> helloAsync(ES_WEBKYSO.MdmsService.helloRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/getListMeterListRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/getListMeterListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ES_WEBKYSO.MdmsService.getListMeterListResponse getListMeterList(ES_WEBKYSO.MdmsService.getListMeterListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/getListMeterListRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/getListMeterListResponse")]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getListMeterListResponse> getListMeterListAsync(ES_WEBKYSO.MdmsService.getListMeterListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/getListMeterListBySerialsRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/getListMeterListBySerialsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ES_WEBKYSO.MdmsService.getListMeterListBySerialsResponse getListMeterListBySerials(ES_WEBKYSO.MdmsService.getListMeterListBySerialsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.mdms.ftu.com/mdms_service/getListMeterListBySerialsRequest", ReplyAction="http://service.mdms.ftu.com/mdms_service/getListMeterListBySerialsResponse")]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getListMeterListBySerialsResponse> getListMeterListBySerialsAsync(ES_WEBKYSO.MdmsService.getListMeterListBySerialsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBCTData_Ngay", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class getBCTData_NgayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg3;
        
        public getBCTData_NgayRequest() {
        }
        
        public getBCTData_NgayRequest(string arg0, string arg1, int arg2, int arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBCTData_NgayResponse", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class getBCTData_NgayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getBCTData_NgayResponse() {
        }
        
        public getBCTData_NgayResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListBCTData_Ngay", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class getListBCTData_NgayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg3;
        
        public getListBCTData_NgayRequest() {
        }
        
        public getListBCTData_NgayRequest(string[] arg0, string arg1, int arg2, int arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListBCTData_NgayResponse", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class getListBCTData_NgayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getListBCTData_NgayResponse() {
        }
        
        public getListBCTData_NgayResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.mdms.ftu.com/")]
    public partial class getBillingDataFromMDMSTable1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mA_NVGCSField;
        
        private string mA_KHANGField;
        
        private string mA_DDOField;
        
        private string mA_DVIQLYField;
        
        private string mA_GCField;
        
        private string mA_QUYENField;
        
        private string mA_TRAMField;
        
        private long bOCSO_IDField;
        
        private bool bOCSO_IDFieldSpecified;
        
        private string lOAI_BCSField;
        
        private string lOAI_CSField;
        
        private string tEN_KHANGField;
        
        private string dIA_CHIField;
        
        private string mA_NNField;
        
        private string sO_HOField;
        
        private string mA_CTOField;
        
        private string sERY_CTOField;
        
        private string hSNField;
        
        private string cS_CUField;
        
        private string tTR_CUField;
        
        private string sL_CUField;
        
        private string sL_TTIEPField;
        
        private string nGAY_CUField;
        
        private string cS_MOIField;
        
        private string tTR_MOIField;
        
        private string sL_MOIField;
        
        private string cHUOI_GIAField;
        
        private long kyField;
        
        private bool kyFieldSpecified;
        
        private long tHANGField;
        
        private bool tHANGFieldSpecified;
        
        private long nAMField;
        
        private bool nAMFieldSpecified;
        
        private string nGAY_MOIField;
        
        private string nGUOI_GCSField;
        
        private string sL_THAOField;
        
        private long kIMUA_CSPKField;
        
        private bool kIMUA_CSPKFieldSpecified;
        
        private string mA_COTField;
        
        private string sLUONG_1Field;
        
        private string sLUONG_2Field;
        
        private string sLUONG_3Field;
        
        private string sO_HOMField;
        
        private string pMAXField;
        
        private string nGAY_PMAXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MA_NVGCS {
            get {
                return this.mA_NVGCSField;
            }
            set {
                this.mA_NVGCSField = value;
                this.RaisePropertyChanged("MA_NVGCS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MA_KHANG {
            get {
                return this.mA_KHANGField;
            }
            set {
                this.mA_KHANGField = value;
                this.RaisePropertyChanged("MA_KHANG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MA_DDO {
            get {
                return this.mA_DDOField;
            }
            set {
                this.mA_DDOField = value;
                this.RaisePropertyChanged("MA_DDO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MA_DVIQLY {
            get {
                return this.mA_DVIQLYField;
            }
            set {
                this.mA_DVIQLYField = value;
                this.RaisePropertyChanged("MA_DVIQLY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MA_GC {
            get {
                return this.mA_GCField;
            }
            set {
                this.mA_GCField = value;
                this.RaisePropertyChanged("MA_GC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MA_QUYEN {
            get {
                return this.mA_QUYENField;
            }
            set {
                this.mA_QUYENField = value;
                this.RaisePropertyChanged("MA_QUYEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MA_TRAM {
            get {
                return this.mA_TRAMField;
            }
            set {
                this.mA_TRAMField = value;
                this.RaisePropertyChanged("MA_TRAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long BOCSO_ID {
            get {
                return this.bOCSO_IDField;
            }
            set {
                this.bOCSO_IDField = value;
                this.RaisePropertyChanged("BOCSO_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BOCSO_IDSpecified {
            get {
                return this.bOCSO_IDFieldSpecified;
            }
            set {
                this.bOCSO_IDFieldSpecified = value;
                this.RaisePropertyChanged("BOCSO_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string LOAI_BCS {
            get {
                return this.lOAI_BCSField;
            }
            set {
                this.lOAI_BCSField = value;
                this.RaisePropertyChanged("LOAI_BCS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string LOAI_CS {
            get {
                return this.lOAI_CSField;
            }
            set {
                this.lOAI_CSField = value;
                this.RaisePropertyChanged("LOAI_CS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string TEN_KHANG {
            get {
                return this.tEN_KHANGField;
            }
            set {
                this.tEN_KHANGField = value;
                this.RaisePropertyChanged("TEN_KHANG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string DIA_CHI {
            get {
                return this.dIA_CHIField;
            }
            set {
                this.dIA_CHIField = value;
                this.RaisePropertyChanged("DIA_CHI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string MA_NN {
            get {
                return this.mA_NNField;
            }
            set {
                this.mA_NNField = value;
                this.RaisePropertyChanged("MA_NN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SO_HO {
            get {
                return this.sO_HOField;
            }
            set {
                this.sO_HOField = value;
                this.RaisePropertyChanged("SO_HO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string MA_CTO {
            get {
                return this.mA_CTOField;
            }
            set {
                this.mA_CTOField = value;
                this.RaisePropertyChanged("MA_CTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string SERY_CTO {
            get {
                return this.sERY_CTOField;
            }
            set {
                this.sERY_CTOField = value;
                this.RaisePropertyChanged("SERY_CTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string HSN {
            get {
                return this.hSNField;
            }
            set {
                this.hSNField = value;
                this.RaisePropertyChanged("HSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string CS_CU {
            get {
                return this.cS_CUField;
            }
            set {
                this.cS_CUField = value;
                this.RaisePropertyChanged("CS_CU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string TTR_CU {
            get {
                return this.tTR_CUField;
            }
            set {
                this.tTR_CUField = value;
                this.RaisePropertyChanged("TTR_CU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string SL_CU {
            get {
                return this.sL_CUField;
            }
            set {
                this.sL_CUField = value;
                this.RaisePropertyChanged("SL_CU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string SL_TTIEP {
            get {
                return this.sL_TTIEPField;
            }
            set {
                this.sL_TTIEPField = value;
                this.RaisePropertyChanged("SL_TTIEP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string NGAY_CU {
            get {
                return this.nGAY_CUField;
            }
            set {
                this.nGAY_CUField = value;
                this.RaisePropertyChanged("NGAY_CU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string CS_MOI {
            get {
                return this.cS_MOIField;
            }
            set {
                this.cS_MOIField = value;
                this.RaisePropertyChanged("CS_MOI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string TTR_MOI {
            get {
                return this.tTR_MOIField;
            }
            set {
                this.tTR_MOIField = value;
                this.RaisePropertyChanged("TTR_MOI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string SL_MOI {
            get {
                return this.sL_MOIField;
            }
            set {
                this.sL_MOIField = value;
                this.RaisePropertyChanged("SL_MOI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string CHUOI_GIA {
            get {
                return this.cHUOI_GIAField;
            }
            set {
                this.cHUOI_GIAField = value;
                this.RaisePropertyChanged("CHUOI_GIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public long KY {
            get {
                return this.kyField;
            }
            set {
                this.kyField = value;
                this.RaisePropertyChanged("KY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KYSpecified {
            get {
                return this.kyFieldSpecified;
            }
            set {
                this.kyFieldSpecified = value;
                this.RaisePropertyChanged("KYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public long THANG {
            get {
                return this.tHANGField;
            }
            set {
                this.tHANGField = value;
                this.RaisePropertyChanged("THANG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool THANGSpecified {
            get {
                return this.tHANGFieldSpecified;
            }
            set {
                this.tHANGFieldSpecified = value;
                this.RaisePropertyChanged("THANGSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public long NAM {
            get {
                return this.nAMField;
            }
            set {
                this.nAMField = value;
                this.RaisePropertyChanged("NAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAMSpecified {
            get {
                return this.nAMFieldSpecified;
            }
            set {
                this.nAMFieldSpecified = value;
                this.RaisePropertyChanged("NAMSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string NGAY_MOI {
            get {
                return this.nGAY_MOIField;
            }
            set {
                this.nGAY_MOIField = value;
                this.RaisePropertyChanged("NGAY_MOI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string NGUOI_GCS {
            get {
                return this.nGUOI_GCSField;
            }
            set {
                this.nGUOI_GCSField = value;
                this.RaisePropertyChanged("NGUOI_GCS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string SL_THAO {
            get {
                return this.sL_THAOField;
            }
            set {
                this.sL_THAOField = value;
                this.RaisePropertyChanged("SL_THAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public long KIMUA_CSPK {
            get {
                return this.kIMUA_CSPKField;
            }
            set {
                this.kIMUA_CSPKField = value;
                this.RaisePropertyChanged("KIMUA_CSPK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KIMUA_CSPKSpecified {
            get {
                return this.kIMUA_CSPKFieldSpecified;
            }
            set {
                this.kIMUA_CSPKFieldSpecified = value;
                this.RaisePropertyChanged("KIMUA_CSPKSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string MA_COT {
            get {
                return this.mA_COTField;
            }
            set {
                this.mA_COTField = value;
                this.RaisePropertyChanged("MA_COT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string SLUONG_1 {
            get {
                return this.sLUONG_1Field;
            }
            set {
                this.sLUONG_1Field = value;
                this.RaisePropertyChanged("SLUONG_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string SLUONG_2 {
            get {
                return this.sLUONG_2Field;
            }
            set {
                this.sLUONG_2Field = value;
                this.RaisePropertyChanged("SLUONG_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string SLUONG_3 {
            get {
                return this.sLUONG_3Field;
            }
            set {
                this.sLUONG_3Field = value;
                this.RaisePropertyChanged("SLUONG_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string SO_HOM {
            get {
                return this.sO_HOMField;
            }
            set {
                this.sO_HOMField = value;
                this.RaisePropertyChanged("SO_HOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string PMAX {
            get {
                return this.pMAXField;
            }
            set {
                this.pMAXField = value;
                this.RaisePropertyChanged("PMAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string NGAY_PMAX {
            get {
                return this.nGAY_PMAXField;
            }
            set {
                this.nGAY_PMAXField = value;
                this.RaisePropertyChanged("NGAY_PMAX");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.mdms.ftu.com/")]
    public partial class getBillingDataFromMDMSResponseTable1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mA_NVGCSField;
        
        private string mA_KHANGField;
        
        private string mA_DDOField;
        
        private string mA_DVIQLYField;
        
        private string mA_GCField;
        
        private string mA_QUYENField;
        
        private string mA_TRAMField;
        
        private long bOCSO_IDField;
        
        private bool bOCSO_IDFieldSpecified;
        
        private string lOAI_BCSField;
        
        private string lOAI_CSField;
        
        private string tEN_KHANGField;
        
        private string dIA_CHIField;
        
        private string mA_NNField;
        
        private string sO_HOField;
        
        private string mA_CTOField;
        
        private string sERY_CTOField;
        
        private string hSNField;
        
        private string cS_CUField;
        
        private string tTR_CUField;
        
        private string sL_CUField;
        
        private string sL_TTIEPField;
        
        private string nGAY_CUField;
        
        private string cS_MOIField;
        
        private string tTR_MOIField;
        
        private string sL_MOIField;
        
        private string cHUOI_GIAField;
        
        private long kyField;
        
        private bool kyFieldSpecified;
        
        private long tHANGField;
        
        private bool tHANGFieldSpecified;
        
        private long nAMField;
        
        private bool nAMFieldSpecified;
        
        private string nGAY_MOIField;
        
        private string nGUOI_GCSField;
        
        private string sL_THAOField;
        
        private long kIMUA_CSPKField;
        
        private bool kIMUA_CSPKFieldSpecified;
        
        private string mA_COTField;
        
        private string sLUONG_1Field;
        
        private string sLUONG_2Field;
        
        private string sLUONG_3Field;
        
        private string sO_HOMField;
        
        private string pMAXField;
        
        private string nGAY_PMAXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MA_NVGCS {
            get {
                return this.mA_NVGCSField;
            }
            set {
                this.mA_NVGCSField = value;
                this.RaisePropertyChanged("MA_NVGCS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MA_KHANG {
            get {
                return this.mA_KHANGField;
            }
            set {
                this.mA_KHANGField = value;
                this.RaisePropertyChanged("MA_KHANG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MA_DDO {
            get {
                return this.mA_DDOField;
            }
            set {
                this.mA_DDOField = value;
                this.RaisePropertyChanged("MA_DDO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MA_DVIQLY {
            get {
                return this.mA_DVIQLYField;
            }
            set {
                this.mA_DVIQLYField = value;
                this.RaisePropertyChanged("MA_DVIQLY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MA_GC {
            get {
                return this.mA_GCField;
            }
            set {
                this.mA_GCField = value;
                this.RaisePropertyChanged("MA_GC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MA_QUYEN {
            get {
                return this.mA_QUYENField;
            }
            set {
                this.mA_QUYENField = value;
                this.RaisePropertyChanged("MA_QUYEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MA_TRAM {
            get {
                return this.mA_TRAMField;
            }
            set {
                this.mA_TRAMField = value;
                this.RaisePropertyChanged("MA_TRAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long BOCSO_ID {
            get {
                return this.bOCSO_IDField;
            }
            set {
                this.bOCSO_IDField = value;
                this.RaisePropertyChanged("BOCSO_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BOCSO_IDSpecified {
            get {
                return this.bOCSO_IDFieldSpecified;
            }
            set {
                this.bOCSO_IDFieldSpecified = value;
                this.RaisePropertyChanged("BOCSO_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string LOAI_BCS {
            get {
                return this.lOAI_BCSField;
            }
            set {
                this.lOAI_BCSField = value;
                this.RaisePropertyChanged("LOAI_BCS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string LOAI_CS {
            get {
                return this.lOAI_CSField;
            }
            set {
                this.lOAI_CSField = value;
                this.RaisePropertyChanged("LOAI_CS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string TEN_KHANG {
            get {
                return this.tEN_KHANGField;
            }
            set {
                this.tEN_KHANGField = value;
                this.RaisePropertyChanged("TEN_KHANG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string DIA_CHI {
            get {
                return this.dIA_CHIField;
            }
            set {
                this.dIA_CHIField = value;
                this.RaisePropertyChanged("DIA_CHI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string MA_NN {
            get {
                return this.mA_NNField;
            }
            set {
                this.mA_NNField = value;
                this.RaisePropertyChanged("MA_NN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SO_HO {
            get {
                return this.sO_HOField;
            }
            set {
                this.sO_HOField = value;
                this.RaisePropertyChanged("SO_HO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string MA_CTO {
            get {
                return this.mA_CTOField;
            }
            set {
                this.mA_CTOField = value;
                this.RaisePropertyChanged("MA_CTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string SERY_CTO {
            get {
                return this.sERY_CTOField;
            }
            set {
                this.sERY_CTOField = value;
                this.RaisePropertyChanged("SERY_CTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string HSN {
            get {
                return this.hSNField;
            }
            set {
                this.hSNField = value;
                this.RaisePropertyChanged("HSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string CS_CU {
            get {
                return this.cS_CUField;
            }
            set {
                this.cS_CUField = value;
                this.RaisePropertyChanged("CS_CU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string TTR_CU {
            get {
                return this.tTR_CUField;
            }
            set {
                this.tTR_CUField = value;
                this.RaisePropertyChanged("TTR_CU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string SL_CU {
            get {
                return this.sL_CUField;
            }
            set {
                this.sL_CUField = value;
                this.RaisePropertyChanged("SL_CU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string SL_TTIEP {
            get {
                return this.sL_TTIEPField;
            }
            set {
                this.sL_TTIEPField = value;
                this.RaisePropertyChanged("SL_TTIEP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string NGAY_CU {
            get {
                return this.nGAY_CUField;
            }
            set {
                this.nGAY_CUField = value;
                this.RaisePropertyChanged("NGAY_CU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string CS_MOI {
            get {
                return this.cS_MOIField;
            }
            set {
                this.cS_MOIField = value;
                this.RaisePropertyChanged("CS_MOI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string TTR_MOI {
            get {
                return this.tTR_MOIField;
            }
            set {
                this.tTR_MOIField = value;
                this.RaisePropertyChanged("TTR_MOI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string SL_MOI {
            get {
                return this.sL_MOIField;
            }
            set {
                this.sL_MOIField = value;
                this.RaisePropertyChanged("SL_MOI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string CHUOI_GIA {
            get {
                return this.cHUOI_GIAField;
            }
            set {
                this.cHUOI_GIAField = value;
                this.RaisePropertyChanged("CHUOI_GIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public long KY {
            get {
                return this.kyField;
            }
            set {
                this.kyField = value;
                this.RaisePropertyChanged("KY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KYSpecified {
            get {
                return this.kyFieldSpecified;
            }
            set {
                this.kyFieldSpecified = value;
                this.RaisePropertyChanged("KYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public long THANG {
            get {
                return this.tHANGField;
            }
            set {
                this.tHANGField = value;
                this.RaisePropertyChanged("THANG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool THANGSpecified {
            get {
                return this.tHANGFieldSpecified;
            }
            set {
                this.tHANGFieldSpecified = value;
                this.RaisePropertyChanged("THANGSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public long NAM {
            get {
                return this.nAMField;
            }
            set {
                this.nAMField = value;
                this.RaisePropertyChanged("NAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAMSpecified {
            get {
                return this.nAMFieldSpecified;
            }
            set {
                this.nAMFieldSpecified = value;
                this.RaisePropertyChanged("NAMSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string NGAY_MOI {
            get {
                return this.nGAY_MOIField;
            }
            set {
                this.nGAY_MOIField = value;
                this.RaisePropertyChanged("NGAY_MOI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string NGUOI_GCS {
            get {
                return this.nGUOI_GCSField;
            }
            set {
                this.nGUOI_GCSField = value;
                this.RaisePropertyChanged("NGUOI_GCS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string SL_THAO {
            get {
                return this.sL_THAOField;
            }
            set {
                this.sL_THAOField = value;
                this.RaisePropertyChanged("SL_THAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public long KIMUA_CSPK {
            get {
                return this.kIMUA_CSPKField;
            }
            set {
                this.kIMUA_CSPKField = value;
                this.RaisePropertyChanged("KIMUA_CSPK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KIMUA_CSPKSpecified {
            get {
                return this.kIMUA_CSPKFieldSpecified;
            }
            set {
                this.kIMUA_CSPKFieldSpecified = value;
                this.RaisePropertyChanged("KIMUA_CSPKSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string MA_COT {
            get {
                return this.mA_COTField;
            }
            set {
                this.mA_COTField = value;
                this.RaisePropertyChanged("MA_COT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string SLUONG_1 {
            get {
                return this.sLUONG_1Field;
            }
            set {
                this.sLUONG_1Field = value;
                this.RaisePropertyChanged("SLUONG_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string SLUONG_2 {
            get {
                return this.sLUONG_2Field;
            }
            set {
                this.sLUONG_2Field = value;
                this.RaisePropertyChanged("SLUONG_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string SLUONG_3 {
            get {
                return this.sLUONG_3Field;
            }
            set {
                this.sLUONG_3Field = value;
                this.RaisePropertyChanged("SLUONG_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string SO_HOM {
            get {
                return this.sO_HOMField;
            }
            set {
                this.sO_HOMField = value;
                this.RaisePropertyChanged("SO_HOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string PMAX {
            get {
                return this.pMAXField;
            }
            set {
                this.pMAXField = value;
                this.RaisePropertyChanged("PMAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string NGAY_PMAX {
            get {
                return this.nGAY_PMAXField;
            }
            set {
                this.nGAY_PMAXField = value;
                this.RaisePropertyChanged("NGAY_PMAX");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBillingDataFromMDMS", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class getBillingDataFromMDMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Table1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ES_WEBKYSO.MdmsService.getBillingDataFromMDMSTable1[] arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public getBillingDataFromMDMSRequest() {
        }
        
        public getBillingDataFromMDMSRequest(ES_WEBKYSO.MdmsService.getBillingDataFromMDMSTable1[] arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBillingDataFromMDMSResponse", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class getBillingDataFromMDMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Table1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ES_WEBKYSO.MdmsService.getBillingDataFromMDMSResponseTable1[] @return;
        
        public getBillingDataFromMDMSResponse() {
        }
        
        public getBillingDataFromMDMSResponse(ES_WEBKYSO.MdmsService.getBillingDataFromMDMSResponseTable1[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBillingSpcFromMDMS", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class getBillingSpcFromMDMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool arg2;
        
        public getBillingSpcFromMDMSRequest() {
        }
        
        public getBillingSpcFromMDMSRequest(string[] arg0, string arg1, bool arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBillingSpcFromMDMSResponse", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class getBillingSpcFromMDMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getBillingSpcFromMDMSResponse() {
        }
        
        public getBillingSpcFromMDMSResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class helloRequest {
        
        public helloRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListMeterList", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class getListMeterListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg0;
        
        public getListMeterListRequest() {
        }
        
        public getListMeterListRequest(string[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListMeterListResponse", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class getListMeterListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getListMeterListResponse() {
        }
        
        public getListMeterListResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListMeterListBySerials", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class getListMeterListBySerialsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg0;
        
        public getListMeterListBySerialsRequest() {
        }
        
        public getListMeterListBySerialsRequest(string[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListMeterListBySerialsResponse", WrapperNamespace="http://service.mdms.ftu.com/", IsWrapped=true)]
    public partial class getListMeterListBySerialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mdms.ftu.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getListMeterListBySerialsResponse() {
        }
        
        public getListMeterListBySerialsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mdms_serviceChannel : ES_WEBKYSO.MdmsService.mdms_service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mdms_serviceClient : System.ServiceModel.ClientBase<ES_WEBKYSO.MdmsService.mdms_service>, ES_WEBKYSO.MdmsService.mdms_service {
        
        public mdms_serviceClient() {
        }
        
        public mdms_serviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mdms_serviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mdms_serviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mdms_serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ES_WEBKYSO.MdmsService.getBCTData_NgayResponse ES_WEBKYSO.MdmsService.mdms_service.getBCTData_Ngay(ES_WEBKYSO.MdmsService.getBCTData_NgayRequest request) {
            return base.Channel.getBCTData_Ngay(request);
        }
        
        public string getBCTData_Ngay(string arg0, string arg1, int arg2, int arg3) {
            ES_WEBKYSO.MdmsService.getBCTData_NgayRequest inValue = new ES_WEBKYSO.MdmsService.getBCTData_NgayRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            ES_WEBKYSO.MdmsService.getBCTData_NgayResponse retVal = ((ES_WEBKYSO.MdmsService.mdms_service)(this)).getBCTData_Ngay(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getBCTData_NgayResponse> ES_WEBKYSO.MdmsService.mdms_service.getBCTData_NgayAsync(ES_WEBKYSO.MdmsService.getBCTData_NgayRequest request) {
            return base.Channel.getBCTData_NgayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getBCTData_NgayResponse> getBCTData_NgayAsync(string arg0, string arg1, int arg2, int arg3) {
            ES_WEBKYSO.MdmsService.getBCTData_NgayRequest inValue = new ES_WEBKYSO.MdmsService.getBCTData_NgayRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((ES_WEBKYSO.MdmsService.mdms_service)(this)).getBCTData_NgayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ES_WEBKYSO.MdmsService.getListBCTData_NgayResponse ES_WEBKYSO.MdmsService.mdms_service.getListBCTData_Ngay(ES_WEBKYSO.MdmsService.getListBCTData_NgayRequest request) {
            return base.Channel.getListBCTData_Ngay(request);
        }
        
        public string getListBCTData_Ngay(string[] arg0, string arg1, int arg2, int arg3) {
            ES_WEBKYSO.MdmsService.getListBCTData_NgayRequest inValue = new ES_WEBKYSO.MdmsService.getListBCTData_NgayRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            ES_WEBKYSO.MdmsService.getListBCTData_NgayResponse retVal = ((ES_WEBKYSO.MdmsService.mdms_service)(this)).getListBCTData_Ngay(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getListBCTData_NgayResponse> ES_WEBKYSO.MdmsService.mdms_service.getListBCTData_NgayAsync(ES_WEBKYSO.MdmsService.getListBCTData_NgayRequest request) {
            return base.Channel.getListBCTData_NgayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getListBCTData_NgayResponse> getListBCTData_NgayAsync(string[] arg0, string arg1, int arg2, int arg3) {
            ES_WEBKYSO.MdmsService.getListBCTData_NgayRequest inValue = new ES_WEBKYSO.MdmsService.getListBCTData_NgayRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((ES_WEBKYSO.MdmsService.mdms_service)(this)).getListBCTData_NgayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ES_WEBKYSO.MdmsService.getBillingDataFromMDMSResponse ES_WEBKYSO.MdmsService.mdms_service.getBillingDataFromMDMS(ES_WEBKYSO.MdmsService.getBillingDataFromMDMSRequest request) {
            return base.Channel.getBillingDataFromMDMS(request);
        }
        
        public ES_WEBKYSO.MdmsService.getBillingDataFromMDMSResponseTable1[] getBillingDataFromMDMS(ES_WEBKYSO.MdmsService.getBillingDataFromMDMSTable1[] arg0, int arg1) {
            ES_WEBKYSO.MdmsService.getBillingDataFromMDMSRequest inValue = new ES_WEBKYSO.MdmsService.getBillingDataFromMDMSRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ES_WEBKYSO.MdmsService.getBillingDataFromMDMSResponse retVal = ((ES_WEBKYSO.MdmsService.mdms_service)(this)).getBillingDataFromMDMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getBillingDataFromMDMSResponse> ES_WEBKYSO.MdmsService.mdms_service.getBillingDataFromMDMSAsync(ES_WEBKYSO.MdmsService.getBillingDataFromMDMSRequest request) {
            return base.Channel.getBillingDataFromMDMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getBillingDataFromMDMSResponse> getBillingDataFromMDMSAsync(ES_WEBKYSO.MdmsService.getBillingDataFromMDMSTable1[] arg0, int arg1) {
            ES_WEBKYSO.MdmsService.getBillingDataFromMDMSRequest inValue = new ES_WEBKYSO.MdmsService.getBillingDataFromMDMSRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ES_WEBKYSO.MdmsService.mdms_service)(this)).getBillingDataFromMDMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSResponse ES_WEBKYSO.MdmsService.mdms_service.getBillingSpcFromMDMS(ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSRequest request) {
            return base.Channel.getBillingSpcFromMDMS(request);
        }
        
        public string getBillingSpcFromMDMS(string[] arg0, string arg1, bool arg2) {
            ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSRequest inValue = new ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSResponse retVal = ((ES_WEBKYSO.MdmsService.mdms_service)(this)).getBillingSpcFromMDMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSResponse> ES_WEBKYSO.MdmsService.mdms_service.getBillingSpcFromMDMSAsync(ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSRequest request) {
            return base.Channel.getBillingSpcFromMDMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSResponse> getBillingSpcFromMDMSAsync(string[] arg0, string arg1, bool arg2) {
            ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSRequest inValue = new ES_WEBKYSO.MdmsService.getBillingSpcFromMDMSRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((ES_WEBKYSO.MdmsService.mdms_service)(this)).getBillingSpcFromMDMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ES_WEBKYSO.MdmsService.helloResponse ES_WEBKYSO.MdmsService.mdms_service.hello(ES_WEBKYSO.MdmsService.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello() {
            ES_WEBKYSO.MdmsService.helloRequest inValue = new ES_WEBKYSO.MdmsService.helloRequest();
            ES_WEBKYSO.MdmsService.helloResponse retVal = ((ES_WEBKYSO.MdmsService.mdms_service)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.helloResponse> ES_WEBKYSO.MdmsService.mdms_service.helloAsync(ES_WEBKYSO.MdmsService.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.helloResponse> helloAsync() {
            ES_WEBKYSO.MdmsService.helloRequest inValue = new ES_WEBKYSO.MdmsService.helloRequest();
            return ((ES_WEBKYSO.MdmsService.mdms_service)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ES_WEBKYSO.MdmsService.getListMeterListResponse ES_WEBKYSO.MdmsService.mdms_service.getListMeterList(ES_WEBKYSO.MdmsService.getListMeterListRequest request) {
            return base.Channel.getListMeterList(request);
        }
        
        public string getListMeterList(string[] arg0) {
            ES_WEBKYSO.MdmsService.getListMeterListRequest inValue = new ES_WEBKYSO.MdmsService.getListMeterListRequest();
            inValue.arg0 = arg0;
            ES_WEBKYSO.MdmsService.getListMeterListResponse retVal = ((ES_WEBKYSO.MdmsService.mdms_service)(this)).getListMeterList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getListMeterListResponse> ES_WEBKYSO.MdmsService.mdms_service.getListMeterListAsync(ES_WEBKYSO.MdmsService.getListMeterListRequest request) {
            return base.Channel.getListMeterListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getListMeterListResponse> getListMeterListAsync(string[] arg0) {
            ES_WEBKYSO.MdmsService.getListMeterListRequest inValue = new ES_WEBKYSO.MdmsService.getListMeterListRequest();
            inValue.arg0 = arg0;
            return ((ES_WEBKYSO.MdmsService.mdms_service)(this)).getListMeterListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ES_WEBKYSO.MdmsService.getListMeterListBySerialsResponse ES_WEBKYSO.MdmsService.mdms_service.getListMeterListBySerials(ES_WEBKYSO.MdmsService.getListMeterListBySerialsRequest request) {
            return base.Channel.getListMeterListBySerials(request);
        }
        
        public string getListMeterListBySerials(string[] arg0) {
            ES_WEBKYSO.MdmsService.getListMeterListBySerialsRequest inValue = new ES_WEBKYSO.MdmsService.getListMeterListBySerialsRequest();
            inValue.arg0 = arg0;
            ES_WEBKYSO.MdmsService.getListMeterListBySerialsResponse retVal = ((ES_WEBKYSO.MdmsService.mdms_service)(this)).getListMeterListBySerials(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getListMeterListBySerialsResponse> ES_WEBKYSO.MdmsService.mdms_service.getListMeterListBySerialsAsync(ES_WEBKYSO.MdmsService.getListMeterListBySerialsRequest request) {
            return base.Channel.getListMeterListBySerialsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ES_WEBKYSO.MdmsService.getListMeterListBySerialsResponse> getListMeterListBySerialsAsync(string[] arg0) {
            ES_WEBKYSO.MdmsService.getListMeterListBySerialsRequest inValue = new ES_WEBKYSO.MdmsService.getListMeterListBySerialsRequest();
            inValue.arg0 = arg0;
            return ((ES_WEBKYSO.MdmsService.mdms_service)(this)).getListMeterListBySerialsAsync(inValue);
        }
    }
}
